export const SYMBOL_DOW_JONES = "^DJI"; // Dow Jone
export const SYMBOL_S_AND_P_500 = "^GSPC"; // S&P 500;
export const SYMBOL_NASDAQ = "^IXIC"; // NASDAQ 


export const UI_PAGE_HOME = "UI_PAGE_HOME";
export const UI_PAGE_COMPARE_STOCK_INDEXES_CHARTS = "UI_PAGE_COMPARE_STOCK_INDEXES_CHARTS";

export const UI_SYMBOL_DETAILS = "UI_SYMBOL_DETAILS";
export const UI_CHART = "UI_CHART";
export const UI_HISTORICAL_DATA = "UI_HISTORICAL_DATA";